### ISSUE TITLE
Discord update

### ISSUE THREAD

**Issue by sniperwolfortiz** [Metalloriff/BetterDiscordPlugins#31]
Due to discords latest update, the plugin has broken. The libraries you use are more than likely the reason why but id check your code to make sure that everything is matching what has been changed.

**Comment by Inve1951** [comment]
what plugin?

**Comment by sniperwolfortiz** [comment]
Sorry, that's my bad I didn't say it before its the detailed server tooltips plugin that is broken. It won't display the plugin due to the guilds being broken or changed within the code. At least that's what the error said.

The full error:

ba07a8562821bfa49397.js:74 DetailedServerTooltips fatal error, plugin could not be started! TypeError: Cannot read property 'guilds' of null
    at Object.getClass (https://rawgit.com/Metalloriff/BetterDiscordPlugins/master/Lib/NeatoBurritoLibrary.js:2312:42)

    at DetailedServerTooltips.onLibLoaded (C:\Users\Owner\AppData\Roaming\BetterDiscord\plugins\DetailedServerTooltips.plugin.js:217:71)

    at libLoadedEvent (C:\Users\Owner\AppData\Roaming\BetterDiscord\plugins\DetailedServerTooltips.plugin.js:39:15)

    at i (https://discordapp.com/assets/ba07a8562821bfa49397.js:74:286804)

**Comment by Metalloriff** [comment]
It should be working with the latest update.
