### ISSUE TITLE
[Issue] [Major] SaveTo no longer works with discord's new context menus. 

### ISSUE THREAD

**Issue by GiovanH** [Metalloriff/BetterDiscordPlugins#92]

**Comment by EliGalaxy** [comment]
+1, it is unusable for now because it doesn't show up on the menu at all.

**Comment by Waterspark63** [comment]
Same here, but it's just a empty transparent box in the context menu for me

**Comment by SakiSakiSakiSakiSaki** [comment]
I have the same problem.

**Comment by Kashotex** [comment]
Yeah same
![Capture](https://user-images.githubusercontent.com/55033374/64927268-67191a80-d7bd-11e9-8ea1-c714e0bb7a6d.PNG)

**Comment by Bakaprime** [comment]
Same problem here.

**Comment by ajtpak** [comment]
please fix it

**Comment by GiovanH** [comment]
I still haven't been able to figure it out but the relevant stacktrace is
```
cc56bc20045414c9e097.js:58 Uncaught DOMException: Failed to read the 'cssRules' property from 'CSSStyleSheet': Cannot access rules
    at a.map.e (https://cdn.staticaly.com/gh/rauenzi/BetterDiscordApp/45916aef50206a8fd7613224cc5d7e52d9f3ef0e/js/main.min.js:55:38297)
    at Array.map (<anonymous>)
    at devMode.getRules (https://cdn.staticaly.com/gh/rauenzi/BetterDiscordApp/45916aef50206a8fd7613224cc5d7e52d9f3ef0e/js/main.min.js:55:38283)
    at devMode.getSelector (https://cdn.staticaly.com/gh/rauenzi/BetterDiscordApp/45916aef50206a8fd7613224cc5d7e52d9f3ef0e/js/main.min.js:55:38566)
    at HTMLDocument.<anonymous> (https://cdn.staticaly.com/gh/rauenzi/BetterDiscordApp/45916aef50206a8fd7613224cc5d7e52d9f3ef0e/js/main.min.js:55:37232)
    at HTMLDocument.dispatch (https://ajax.googleapis.com/ajax/libs/jquery/2.0.0/jquery.min.js:5:9505)
    at HTMLDocument.y.handle (https://ajax.googleapis.com/ajax/libs/jquery/2.0.0/jquery.min.js:5:6288)
    at HTMLDocument.i (https://discordapp.com/assets/cc56bc20045414c9e097.js:58:194859)
i @ cc56bc20045414c9e097.js:58
```

**Comment by GiovanH** [comment]
This is almost definitely an issue with NeatoBurritoLibrary. Will need to hear from @Metalloriff to be sure.
